[package]
name = "marvinvirus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "marvinvirus_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
walkdir.workspace = true
blake3.workspace = true
rayon.workspace = true
trash.workspace = true
dirs.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
time = { version = "0.3", features = ["formatting", "parsing", "serde"] }
uuid = { version = "1", features = ["v4"] }
dunce = "1"

[target.'cfg(windows)'.dependencies]
windows.workspace = true
winreg = "0.52"
